# Generated by Django 4.2.1 on 2023-05-30 07:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_cook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='users/images/', validators=[users.models.validate_image]),
        ),
    ]
