# Generated by Django 4.2.1 on 2023-05-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_quantity_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
