# Generated by Django 4.2.1 on 2023-05-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_in_stock_product_number_in_stock_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-last_update']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id']},
        ),
    ]
