# Generated by Django 4.2.1 on 2023-05-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='author',
        ),
    ]
