# Generated by Django 4.2.1 on 2023-05-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('units_of_measurement', models.CharField(choices=[('ml', 'millilitres'), ('mg', 'milligrams'), ('oz', 'ounces'), ('l', 'litres'), ('gm', 'grams')], max_length=2, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=155, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.ingredient')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
