# Generated by Django 4.2.1 on 2023-05-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_ingredients_ingredient_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
