# Generated by Django 4.2.1 on 2023-05-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_delete_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('units_of_measurement', models.CharField(choices=[('ml', 'millilitres'), ('mg', 'milligrams'), ('oz', 'ounces'), ('l', 'litres'), ('gm', 'grams')], max_length=2, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
